Add workflows and issue templates (#6)

diff --git a/image/scripts/app_launch b/image/scripts/app_launch
--- a/image/scripts/app_launch
+++ b/image/scripts/app_launch
@@ -1,18 +1,22 @@
 #!/bin/bash
 
-cd ${CONTAINER_APP_ROOT}/app
+#Ensure background processes are killed when the script ends, otherwise pebble
+# will never see the process ending and think it's still running
+trap 'trap - SIGTERM && kill 0' SIGINT SIGTERM EXIT
 
-export RAILS_ENV=${DISCOURSE_RAILS_ENVIRONMENT:-production}
+cd "${CONTAINER_APP_ROOT}/app" || exit 1
+
+export RAILS_ENV="${DISCOURSE_RAILS_ENVIRONMENT:-production}"
 export UNICORN_BIND_ALL=0.0.0.0
 export UNICORN_SIDEKIQS=1
 
 # Putting the tail's in the background gets the various logs outputting to
 # stdout. The sed allows us to distinguish where a given log line comes form.
-touch ${CONTAINER_APP_ROOT}/app/log/production.log
-touch ${CONTAINER_APP_ROOT}/app/log/unicorn-stderr.log
-tail -f ${CONTAINER_APP_ROOT}/app/log/production.log |sed 's/^/discourse: /' &
-tail -f ${CONTAINER_APP_ROOT}/app/log/unicorn-stderr.log |sed 's/^/unicorn-error: /' 1>&2 &
+touch "${CONTAINER_APP_ROOT}/app/log/production.log"
+touch "${CONTAINER_APP_ROOT}/app/log/unicorn-stderr.log"
+tail -f "${CONTAINER_APP_ROOT}/app/log/production.log" |sed 's/^/discourse: /' &
+tail -f "${CONTAINER_APP_ROOT}/app/log/unicorn-stderr.log" |sed 's/^/unicorn-error: /' 1>&2 &
 
 # Add the discourse bin and scripts directories to the PATH.
-export PATH=${CONTAINER_APP_ROOT}/app/bin:${CONTAINER_APP_ROOT}/app/scripts:$PATH
-su -s /bin/bash -c "bin/bundle exec unicorn -c ${CONTAINER_APP_ROOT}/app/config/unicorn.conf.rb" ${CONTAINER_APP_USERNAME} 2>&1
+export PATH="${CONTAINER_APP_ROOT}/app/bin:${CONTAINER_APP_ROOT}/app/scripts:$PATH"
+su -s /bin/bash -c "bin/unicorn -c ${CONTAINER_APP_ROOT}/app/config/unicorn.conf.rb" "${CONTAINER_APP_USERNAME}" 2>&1
